"use client"
import { StyleSheet } from "@react-pdf/renderer";



// Create styles
export const styles = StyleSheet.create({
  document: {
    padding: "10px",
  },
  keyText: {
    fontSize: 9,
    fontWeight: "bold",
    padding: "0 5px",
  },
  valueText: {
    fontSize: 9,
    fontWeight: 500,
    padding: "0 5px",
  },
  page: {
    flexDirection: "column",
    backgroundColor: "white",
    gap: "0",
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 10,
  },
  container: {
    border: "1px solid black",
    width: "100%",
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    gap: "0",
  },

  headerSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderBottom: "1px solid black",
    padding: "20px 10px 5px 10px",
    position: "relative",
  },
  logo: {
    position: "absolute",
    left: "10px",
    top: "2px",
    fontSize: "10px",
  },
  pageNumber: {
    position: "absolute",
    right: "10px",
    top: "2px",
    fontSize: "10px",
  },
  title: {
    fontSize: 18,
    fontWeight: "ultrabold",
    textTransform: "uppercase",
  },
  reportInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderBottom: "1px solid black",
    position: "relative",
    marginBottom: "0",
  },
  reportInfoTitle: {
    fontSize: "12px",
    fontWeight: "bold",
    marginBottom: "10px",
  },
  reportInfoSection: {
    display: "flex",
    flexDirection: "row",
    gap: "50px",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    borderBottom: "1px solid black",
    padding: "10px",
  },

  reportInfoSubSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "5px",
    flex: 1,
  },
  reportInfoSubSectionGroup: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  reportInfoSubSectionItem: {
    fontSize: 9,
    fontWeight: 300,
    flex: 1,
    textAlign: "left",
  },

  books: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  },
  book: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    borderBottom: "1px solid black",
    borderTop: "1px solid black",
    height: "100px",
    marginBottom:"40px",
  },
  bookRightSection: {
    flex: 1.3,
    display: "flex",
    flexDirection: "column",
  },
  bookLeftSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid black",
  },
  bookSectionTop: {
    width: "100% !important",
    display: "flex",
    flexDirection: "column",
    height: "40px",
    borderBottom: "1px solid black",
  },
  bookSectionTopRow: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: "20px",
    borderBottom: "1px solid black",
  },
  bookSectionTopRowKey: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "#f2f2f2",
    color: "black",
    flex: 1,
    fontSize: 9,
    borderRight: "1px solid black",
    borderBottom: "1px solid black",
    height: "20px",
    paddingLeft: "10px",
  },
  bookSectionTopRowValue: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    borderBottom: "1px solid black",
    backgroundColor: "white",
    paddingRight: "10px",
    color: "black",
    flex: 1,
    fontSize: 9,
    height: "20px",
  },
  bookSectionBottom: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    fontSize: 9,
  },
  bookSectionBottomColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontSize: 9,
    borderRight: "1px solid black",
    flex: 1,
  },
  bookSectionBottomColumnLast: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontSize: 9,
    flex: 1,
  },
  bookSectionBottomColumnKey: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f2f2f2",
    borderBottom: "1px solid black",
    fontSize: 9,
    width: "100%",
    height: "20px",
  },
  bookSectionBottomColumnValue: {
    backgroundColor: "white",
    borderBottom: "1px solid darkgray",
    fontSize: 9,
    width: "100%",
    height: "20px",
  },
});