services:

  db:
    container_name: NHFC
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nhfc
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

